#!/bin/sh
### BEGIN INIT INFO
# Provides:          ruilbiebdisplay
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start ruilbiebdisplay at boot time
# Description:       Ruilbiebdisplay server
### END INIT INFO

case "$1" in
    start)
        echo "Starting example"
        # run the program you want to start
        java -jar /home/pi/git/ruilbieb/display/target/ruilbiebdisplay-1.0-shaded.jar > /tmp/ruilbieb.log &
    ;;
    stop)
        echo "Stopping example"
        # end the program you want to stop
        killall java
    ;;
    *)
         echo "Usage: /etc/init.d/ruilbiebdisplay {start|stop}"
         exit 1
     ;;
esac

